### ISSUE TITLE
Install v2.2, returns v2.1

### ISSUE THREAD

**Issue by arnaudceol** [kingsfordgroup/armatus#11]
Hi,

I've downloaded and compiled the release 2.2 (tar.gz and zip). But the version returned is 2.1:

 armatus --help

        ***********************************
        ****                           ****
        ****        ARMATUS 2.1        ****
        ****                           ****
        ***********************************

Is the problem the source code or the version number displayed?

thanks

**Comment by arnaudceol** [comment]
Some options from version 2.2 are missing, so I guess this is indeed version 2.1.

**Comment by kingsfordgroup** [comment]
It was unfortunately a bit of a mess. The release *is* 2.2, but reports 2.1, and README describes new features for the (yet unreleased) 2.3 in the code since 2.2 but calls them 2.2. To fix all this, I just created a new release, 2.3 which contains the current source code and matches the readme. Binaries for MacOS and Ubuntu are included. As always, they depend on boost.

**Comment by arnaudceol** [comment]
Great, thanks!
